/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Query */
        post: operations["post_query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corpora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Corpora */
        get: operations["list_corpora_corpora_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corpora/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Corpus */
        post: operations["ingest_corpus_corpora_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Receipts */
        get: operations["list_receipts_receipts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Eval Runs */
        get: operations["list_eval_runs_eval_runs_get"];
        put?: never;
        /** Create Eval Run */
        post: operations["create_eval_run_eval_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Job */
        post: operations["resume_job_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_ingest_corpus_corpora_ingest_post */
        Body_ingest_corpus_corpora_ingest_post: {
            /** Corpus Id */
            corpus_id: string;
            /** Files */
            files: string[];
        };
        /** CitationModel */
        CitationModel: {
            /** N */
            n: number;
            /** Chunk Id */
            chunk_id: string;
            /** Passage Id */
            passage_id: string;
            /** Text */
            text: string;
            /** Score */
            score: number;
        };
        /** CorporaResponse */
        CorporaResponse: {
            /** Corpora */
            corpora: components["schemas"]["CorpusModel"][];
        };
        /** CorpusModel */
        CorpusModel: {
            /** Corpus Id */
            corpus_id: string;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
        };
        /** CostEstimateModel */
        CostEstimateModel: {
            /** N Queries */
            n_queries: number;
            /** Est Tokens */
            est_tokens: number;
            /** Est Usd */
            est_usd: number;
            /** Pricing Table Version */
            pricing_table_version: string;
        };
        /** EvalRunListItem */
        EvalRunListItem: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Corpus Id */
            corpus_id: string;
            /** Preset */
            preset: string;
            /** Slice */
            slice: string;
            /** Created At */
            created_at: number;
        };
        /** EvalRunRequest */
        EvalRunRequest: {
            /** Corpus Id */
            corpus_id: string;
            /** Preset */
            preset: string;
            /**
             * Slice
             * @default smoke
             * @enum {string}
             */
            slice: "smoke" | "full";
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
            /**
             * Spend Cap Usd
             * @default 5
             */
            spend_cap_usd: number;
        };
        /** EvalRunResponse */
        EvalRunResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "needs_confirmation" | "started";
            estimate: components["schemas"]["CostEstimateModel"];
            /** Job Id */
            job_id?: string | null;
        };
        /** EvalRunsResponse */
        EvalRunsResponse: {
            /** Runs */
            runs: components["schemas"]["EvalRunListItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Vendors */
            vendors: components["schemas"]["VendorStatusModel"][];
            /** Qdrant Ok */
            qdrant_ok: boolean;
            /** Missing Env Vars */
            missing_env_vars: string[];
            /** Testing Mode */
            testing_mode: boolean;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Job Id */
            job_id: string;
            /** Corpus Id */
            corpus_id: string;
        };
        /** JobEventModel */
        JobEventModel: {
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /** Message */
            message: string;
            /** Progress */
            progress: number;
        };
        /** JobResponse */
        JobResponse: {
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "interrupted";
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
            /** Events */
            events: components["schemas"]["JobEventModel"][];
        };
        /** QueryRequest */
        QueryRequest: {
            /** Query */
            query: string;
            /** Corpus Id */
            corpus_id: string;
            /** Preset */
            preset: string;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Abstained */
            abstained: boolean;
            /**
             * Route
             * @enum {string}
             */
            route: "s1" | "s2" | "graph";
            /** Degraded */
            degraded: string[];
            /** Citations */
            citations: components["schemas"]["CitationModel"][];
            /** Trace Id */
            trace_id: string;
        };
        /** ReceiptEntryModel */
        ReceiptEntryModel: {
            /**
             * Source
             * @enum {string}
             */
            source: "committed" | "local";
            /** Path */
            path: string;
            /** Schema Version */
            schema_version: number;
            /** Receipt */
            receipt: {
                [key: string]: unknown;
            };
        };
        /** ReceiptsResponse */
        ReceiptsResponse: {
            /** Receipts */
            receipts: components["schemas"]["ReceiptEntryModel"][];
            /** Errors */
            errors: string[];
        };
        /** TraceEventModel */
        TraceEventModel: {
            /** Trace Id */
            trace_id: string;
            /** Seq */
            seq: number;
            /** Node */
            node: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Model */
            model: string | null;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Duration Ms */
            duration_ms: number;
        };
        /** TraceResponse */
        TraceResponse: {
            /** Trace Id */
            trace_id: string;
            /** Events */
            events: components["schemas"]["TraceEventModel"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VendorStatusModel */
        VendorStatusModel: {
            /** Name */
            name: string;
            /** Configured */
            configured: boolean;
            /** Env Var */
            env_var: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    post_query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_corpora_corpora_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorporaResponse"];
                };
            };
        };
    };
    ingest_corpus_corpora_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_corpus_corpora_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_receipts_receipts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptsResponse"];
                };
            };
        };
    };
    list_eval_runs_eval_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunsResponse"];
                };
            };
        };
    };
    create_eval_run_eval_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_job_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
